// ClockAlarmActivity.kt
package com.example.purramid.purramidtime.clock

import android.Manifest
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.media.MediaPlayer
import android.os.Build
import android.os.Bundle
import android.os.VibrationEffect
import android.os.Vibrator
import android.os.VibratorManager
import android.util.Log
import android.widget.Button
import android.widget.EditText
import android.widget.TextView
import android.widget.TimePicker
import androidx.annotation.RequiresPermission
import androidx.appcompat.app.AppCompatActivity
import androidx.appcompat.widget.SwitchCompat
import androidx.lifecycle.lifecycleScope
import com.example.purramid.purramidtime.R
import com.example.purramid.purramidtime.data.db.ClockAlarmDao
import com.example.purramid.purramidtime.data.db.ClockAlarmEntity
import com.google.android.material.snackbar.Snackbar
import dagger.hilt.android.AndroidEntryPoint
import kotlinx.coroutines.launch
import java.time.LocalTime
import java.time.ZoneId
import javax.inject.Inject

@AndroidEntryPoint
class ClockAlarmActivity : AppCompatActivity() {

    @Inject lateinit var alarmDao: ClockAlarmDao

    private lateinit var timePicker: TimePicker
    private lateinit var labelEditText: EditText
    private lateinit var soundSwitch: SwitchCompat
    private lateinit var vibrationSwitch: SwitchCompat
    private lateinit var saveButton: Button
    private lateinit var cancelButton: Button

    private var instanceId: Int = -1
    private var editingAlarmId: Long = -1

    companion object {
        private const val TAG = "ClockAlarmActivity"
        const val EXTRA_CLOCK_ID = "clock_id"
        const val EXTRA_ALARM_ID = "alarm_id" // For editing existing alarms
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_clock_alarm)

        instanceId = intent.getIntExtra(EXTRA_CLOCK_ID, -1)
        editingAlarmId = intent.getLongExtra(EXTRA_ALARM_ID, -1)

        if (instanceId == -1) {
            Snackbar.make(findViewById(android.R.id.content), R.string.alarm_invalid_clock, Snackbar.LENGTH_SHORT).show()
            finish()
            return
        }

        initializeViews()
        setupListeners()

        if (editingAlarmId != -1L) {
            loadExistingAlarm()
        }
    }

    private fun initializeViews() {
        timePicker = findViewById(R.id.timePicker)
        labelEditText = findViewById(R.id.labelEditText)
        soundSwitch = findViewById(R.id.soundSwitch)
        vibrationSwitch = findViewById(R.id.vibrationSwitch)
        saveButton = findViewById(R.id.saveButton)
        cancelButton = findViewById(R.id.cancelButton)

        // Set 24-hour format
        timePicker.setIs24HourView(true)
    }

    private fun setupListeners() {
        saveButton.setOnClickListener {
            saveAlarm()
        }

        cancelButton.setOnClickListener {
            finish()
        }
    }

    private fun loadExistingAlarm() {
        lifecycleScope.launch {
            val alarm = alarmDao.getAlarmById(editingAlarmId)
            alarm?.let {
                timePicker.hour = it.time.hour
                timePicker.minute = it.time.minute
                labelEditText.setText(it.label)
                soundSwitch.isChecked = it.soundEnabled
                vibrationSwitch.isChecked = it.vibrationEnabled
            }
        }
    }

    private fun saveAlarm() {
        val time = LocalTime.of(timePicker.hour, timePicker.minute)
        val label = labelEditText.text.toString()
        val soundEnabled = soundSwitch.isChecked
        val vibrationEnabled = vibrationSwitch.isChecked

        lifecycleScope.launch {
            try {
                var alarm = ClockAlarmEntity(
                    alarmId = if (editingAlarmId != -1L) editingAlarmId else 0,
                    instanceId = instanceId,
                    time = time,
                    label = label,
                    soundEnabled = soundEnabled,
                    vibrationEnabled = vibrationEnabled
                )

                if (editingAlarmId != -1L) {
                    alarmDao.updateAlarm(alarm)
                } else {
                    // Insert returns the autogenerated id; needed so the PendingIntent
                    // request code matches on later edit/cancel.
                    val newId = alarmDao.insertAlarm(alarm)
                    alarm = alarm.copy(alarmId = newId)
                }

                // Schedule the alarm
                val exact = AlarmScheduler.schedule(this@ClockAlarmActivity, alarm)

                showAlarmConfirmation(alarm, exact)
                finish()
            } catch (e: Exception) {
                Log.e(TAG, "Error saving alarm", e)
                Snackbar.make(findViewById(android.R.id.content), R.string.alarm_error_saving, Snackbar.LENGTH_SHORT).show()
            }
        }
    }

    private fun showAlarmConfirmation(alarm: ClockAlarmEntity, exact: Boolean) {
        val timeString = String.format("%02d:%02d", alarm.time.hour, alarm.time.minute)
        val timeZoneName = ZoneId.of(alarm.timeZoneId ?: ZoneId.systemDefault().id).id

        val message = if (alarm.label.isNotEmpty()) {
            getString(R.string.alarm_set_message_labeled, alarm.label, timeString, timeZoneName)
        } else {
            getString(R.string.alarm_set_message, timeString, timeZoneName)
        }

        val snackbar = Snackbar.make(findViewById(android.R.id.content), message, Snackbar.LENGTH_LONG)
        if (!exact) {
            // Let the teacher know timing is approximate and how to fix it.
            snackbar.setText(getString(R.string.alarm_set_inexact, message))
        }
        snackbar.show()
    }
}

// Alarm Receiver for handling alarm triggers
class AlarmReceiver : BroadcastReceiver() {
    override fun onReceive(context: Context, intent: Intent) {
        val alarmId = intent.getLongExtra(AlarmScheduler.EXTRA_ALARM_ID, -1)
        val instanceId = intent.getIntExtra(AlarmScheduler.EXTRA_CLOCK_ID, -1)
        val label = intent.getStringExtra(AlarmScheduler.EXTRA_LABEL) ?: ""
        val soundEnabled = intent.getBooleanExtra(AlarmScheduler.EXTRA_SOUND_ENABLED, true)
        val vibrationEnabled = intent.getBooleanExtra(AlarmScheduler.EXTRA_VIBRATION_ENABLED, true)

        Log.d("AlarmReceiver", "Alarm triggered: $alarmId for clock $instanceId")

        // Launch the full-screen ringing UI. Allowed from the background because the
        // app holds SYSTEM_ALERT_WINDOW (see AndroidManifest).
        val alarmIntent = Intent(context, AlarmRingingActivity::class.java).apply {
            flags = Intent.FLAG_ACTIVITY_NEW_TASK
            putExtra(AlarmScheduler.EXTRA_ALARM_ID, alarmId)
            putExtra(AlarmScheduler.EXTRA_CLOCK_ID, instanceId)
            putExtra(AlarmScheduler.EXTRA_LABEL, label)
            putExtra(AlarmScheduler.EXTRA_SOUND_ENABLED, soundEnabled)
            putExtra(AlarmScheduler.EXTRA_VIBRATION_ENABLED, vibrationEnabled)
        }
        context.startActivity(alarmIntent)
    }
}

// Full-screen alarm ringing activity
@AndroidEntryPoint
class AlarmRingingActivity : AppCompatActivity() {

    @Inject lateinit var alarmDao: ClockAlarmDao

    private var mediaPlayer: MediaPlayer? = null
    private var vibrator: Vibrator? = null
    private var alarmId: Long = -1

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        showWhenLockedAndTurnScreenOn()
        setContentView(R.layout.activity_alarm_ringing)

        alarmId = intent.getLongExtra(AlarmScheduler.EXTRA_ALARM_ID, -1)
        val label = intent.getStringExtra(AlarmScheduler.EXTRA_LABEL) ?: ""
        val soundEnabled = intent.getBooleanExtra(AlarmScheduler.EXTRA_SOUND_ENABLED, true)
        val vibrationEnabled = intent.getBooleanExtra(AlarmScheduler.EXTRA_VIBRATION_ENABLED, true)

        // Set up UI
        findViewById<TextView>(R.id.alarmLabel).text = label.ifEmpty { getString(R.string.alarm) }
        findViewById<TextView>(R.id.timeDisplay).text =
            LocalTime.now().let { String.format("%02d:%02d", it.hour, it.minute) }

        // Start sound and vibration
        if (soundEnabled) {
            startAlarmSound()
        }

        if (vibrationEnabled) {
            startVibration()
        }

        // Set up dismiss button
        findViewById<Button>(R.id.dismissButton).setOnClickListener {
            dismiss()
        }
    }

    /** Ensures the alarm is visible on a locked/asleep panel (spec: same as system alarm). */
    private fun showWhenLockedAndTurnScreenOn() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O_MR1) {
            setShowWhenLocked(true)
            setTurnScreenOn(true)
        } else {
            @Suppress("DEPRECATION")
            window.addFlags(
                android.view.WindowManager.LayoutParams.FLAG_SHOW_WHEN_LOCKED or
                    android.view.WindowManager.LayoutParams.FLAG_TURN_SCREEN_ON or
                    android.view.WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON
            )
        }
    }

    private fun dismiss() {
        stopAlarm()
        // A one-time alarm has fired; mark it inactive so it does not linger as "active"
        // (spec 2.6.1/2.6.2: alarms persist whether active or not).
        if (alarmId != -1L) {
            val dao = alarmDao
            lifecycleScope.launch {
                dao.setAlarmEnabled(alarmId, false)
            }
        }
        finish()
    }

    private fun startAlarmSound() {
        mediaPlayer = MediaPlayer.create(this, R.raw.alarm_sound)
        mediaPlayer?.isLooping = true
        mediaPlayer?.start()
    }

    @RequiresPermission(Manifest.permission.VIBRATE)
    private fun startVibration() {
        vibrator = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            val vibratorManager = getSystemService(Context.VIBRATOR_MANAGER_SERVICE) as VibratorManager
            vibratorManager.defaultVibrator
        } else {
            @Suppress("DEPRECATION")
            getSystemService(Context.VIBRATOR_SERVICE) as Vibrator
        }

        val pattern = longArrayOf(0, 1000, 500, 1000) // Vibrate pattern
        vibrator?.vibrate(VibrationEffect.createWaveform(pattern, 0))
    }

    private fun stopAlarm() {
        mediaPlayer?.stop()
        mediaPlayer?.release()
        mediaPlayer = null

        vibrator?.cancel()
        vibrator = null
    }

    override fun onDestroy() {
        super.onDestroy()
        stopAlarm()
    }
}
